import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { cookies, headers } from "next/headers";
import { UiHeader } from "@/components";

const inter = Onest({
  subsets: ["latin"],
  style: ["normal", "normal"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--onset",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  console.log("🚀 ~ theme:", theme);

  return (
    <html
      lang="en"
      data-theme={theme?.value || "system"}
      className={inter.className}
    >
      <body>
        <UiHeader />
        {children}
      </body>
    </html>
  );
}
